"use client";

import { audioContextManager } from "@/lib/audioContextManager";
import { useFlyStore } from "@/store/fly";
import { useEffect } from "react";

const MAX_FLY_PAN = 0.8;

export const FlyAudioController = () => {
  const enabled = useFlyStore((state) => state.enabled);
  const mode = useFlyStore((state) => state.mode);
  const width = useFlyStore((state) => state.width);
  const cycleSeconds = useFlyStore((state) => state.cycleSeconds);
  const manualPan = useFlyStore((state) => state.manualPan);

  // Audio movement is generated by an oscillator in the Web Audio graph. It
  // keeps running across background-tab throttling and replacement track nodes.
  useEffect(() => {
    if (!enabled) {
      audioContextManager.disableFly();
      useFlyStore.getState().setCurrentPan(0);
      return;
    }

    audioContextManager.getContext();
    void audioContextManager.resume().catch(() => {});

    if (mode === "auto") {
      audioContextManager.setFlyAuto(width * MAX_FLY_PAN, cycleSeconds);
    } else {
      audioContextManager.setFlyManual(manualPan * width * MAX_FLY_PAN);
    }
  }, [cycleSeconds, enabled, manualPan, mode, width]);

  // requestAnimationFrame is visual-only. When it resumes after a background
  // pause, it reads the live LFO value and immediately catches up with audio.
  useEffect(() => {
    if (!enabled) return;
    let frame = 0;
    let lastUpdate = 0;

    const tick = (now: number) => {
      if (now - lastUpdate >= 33) {
        useFlyStore.getState().setCurrentPan(audioContextManager.getCurrentFlyPan());
        lastUpdate = now;
      }
      frame = requestAnimationFrame(tick);
    };

    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [enabled]);

  return null;
};
